import { lazy } from 'react';

// Retry wrapper for lazy imports — handles chunk load failures after deployments
const retryLazy = (fn) => lazy(() => fn().catch(() => { window.location.reload(); return fn(); }));

// Core Services
export const DiaGynRedesigned = lazy(() => import('@/pages/DiaGynRedesigned'));
export const Mango = lazy(() => import('@/pages/Mango'));
export const MangoUltrasound = lazy(() => import('@/pages/MangoUltrasound'));
export const Pharmacy = lazy(() => import('@/pages/Pharmacy'));
export const OrangeMedcare = lazy(() => import('@/pages/OrangeMedcare'));
export const OrangeGenerics = lazy(() => import('@/pages/OrangeGenerics'));
export const TrustedFormularyPage = lazy(() => import('@/pages/TrustedFormularyPage'));
export const Nutricare = lazy(() => import('@/pages/Nutricare'));
export const Evara = lazy(() => import('@/pages/Evara'));
export const Glydex = lazy(() => import('@/pages/Glydex'));

// User Pages
export const Profile = lazy(() => import('@/pages/Profile'));
export const AdminPanel = lazy(() => import('@/pages/AdminPanel'));
export const DiaGynStaffPortal = lazy(() => import('@/pages/DiaGynStaffPortal'));
export const OrangePharmacyStaffPortal = lazy(() => import('@/pages/OrangePharmacyStaffPortal'));
export const MangoLabsStaffPortal = lazy(() => import('@/pages/MangoLabsStaffPortal'));
export const TokenDisplay = lazy(() => import('@/pages/TokenDisplay'));
export const DoctorPortalRedesigned = lazy(() => import('@/pages/DoctorPortalRedesigned'));
export const TrackOrder = lazy(() => import('@/pages/TrackOrder'));
export const MyAppointmentsPage = lazy(() => import('@/pages/MyAppointmentsPage'));
export const PatientProfile = lazy(() => import('@/pages/PatientProfile'));
export const OrderTracking = lazy(() => import('@/pages/OrderTracking'));
export const PatientDashboard = lazy(() => import('@/pages/PatientDashboard'));
export const Feedback = lazy(() => import('@/pages/Feedback'));
export const PrivacyPolicy = lazy(() => import('@/pages/PrivacyPolicy'));
export const TermsOfService = lazy(() => import('@/pages/TermsOfService'));
export const AboutUs = lazy(() => import('@/pages/AboutUs'));
export const MembershipPlans = lazy(() => import('@/pages/MembershipPlans'));
export const DoctorProfiles = lazy(() => import('@/pages/DoctorProfiles'));
export const Alyne = lazy(() => import('@/pages/Alyne'));
export const ANCFormPublic = lazy(() => import('@/pages/ANCFormPublic'));
export const DiabetesFormPublic = lazy(() => import('@/pages/DiabetesFormPublic'));
export const QueuePage = lazy(() => import('@/pages/QueuePage'));
export const SettingsPage = lazy(() => import('@/pages/SettingsPage'));
export const PaymentGateway = lazy(() => import('@/pages/PaymentGateway'));
export const PaymentReturn = lazy(() => import('@/pages/PaymentReturn'));
export const PaymentHistoryDashboard = lazy(() => import('@/pages/PaymentHistoryDashboard'));
export const Reneu = lazy(() => import('@/pages/Reneu'));
export const PSVNFoundation = lazy(() => import('@/pages/PSVNFoundation'));
export const MedicineImageUpload = lazy(() => import('@/pages/MedicineImageUpload'));
export const ProtonReportDownload = lazy(() => import('@/pages/ProtonReportDownload'));
export const PharmacyProductPage = lazy(() => import('@/pages/PharmacyProductPage'));
export const PharmacyCategory = lazy(() => import('@/pages/PharmacyCategory'));
export const ShopByBrand = lazy(() => import('@/pages/ShopByBrand'));
export const HowToInstall = lazy(() => import('@/pages/HowToInstall'));
export const NevikaCuraOne = lazy(() => import('@/pages/NevikaCuraOne'));
export const HealthCard = lazy(() => import('@/pages/HealthCard'));
export const GiftHealthCards = lazy(() => import('@/pages/GiftHealthCards'));
export const HealthPlans = lazy(() => import('@/pages/HealthPlans'));
export const CarePackages = lazy(() => import('@/pages/CarePackages'));
export const CuraWallet = lazy(() => import('@/pages/CuraWallet'));
export const CuraOne = lazy(() => import('@/pages/CuraOne'));
export const CuraXCoins = lazy(() => import('@/pages/CuraXCoins'));
export const CuraBonus = lazy(() => import('@/pages/CuraBonus'));
export const SavedAddresses = lazy(() => import('@/pages/SavedAddresses'));
export const FamilyMembers = lazy(() => import('@/pages/FamilyMembers'));
export const MyFavorites = lazy(() => import('@/pages/MyFavorites'));
export const HealthInsights = lazy(() => import('@/pages/HealthInsights'));
export const MedicineScanner = lazy(() => import('@/pages/MedicineScanner'));
export const PaymentMethods = lazy(() => import('@/pages/PaymentMethods'));
export const FamilyWallet = lazy(() => import('@/pages/FamilyWallet'));
export const NevikaLabs = lazy(() => import('@/pages/NevikaLabs'));
export const ProtonDiagnostics = lazy(() => import('@/pages/ProtonDiagnostics'));
export const Nexugene = lazy(() => import('@/pages/Nexugene'));
export const PrescriptionWallet = lazy(() => import('@/pages/PrescriptionWallet'));
export const AppointmentCalendar = lazy(() => import('@/pages/AppointmentCalendar'));
export const PatientLogin = lazy(() => import('@/pages/PatientLogin'));
export const StaffPortalLogin = lazy(() => import('@/pages/StaffPortalLogin'));
export const DoctorPortalLogin = lazy(() => import('@/pages/DoctorPortalLogin'));
export const AdminPortalLogin = lazy(() => import('@/pages/AdminPortalLogin'));
export const DoctorEMRDashboard = lazy(() => import('@/pages/DoctorEMRDashboard'));
export const SuperAdminDashboard = lazy(() => import('@/pages/SuperAdminDashboard'));
export const Checkout = lazy(() => import('@/pages/Checkout'));
export const OnlineAppointmentSuccess = lazy(() => import('@/pages/OnlineAppointmentSuccess'));
export const CartPage = lazy(() => import('@/pages/CartPage'));
export const BookingConfirmationPage = lazy(() => import('@/components/BookingConfirmationPage'));
export const MyOrders = lazy(() => import('@/pages/MyOrders'));
export const PharmacyCheckout = lazy(() => import('@/pages/checkout').then(m => ({ default: m.PharmacyCheckout })));
export const MangoCheckout = lazy(() => import('@/pages/checkout').then(m => ({ default: m.MangoCheckout })));
export const MangoCategory = lazy(() => import('@/pages/MangoCategory'));
export const UnifiedCheckout = lazy(() => import('@/pages/checkout/UnifiedCheckout'));
export const HealthTimeline = lazy(() => import('@/pages/HealthTimeline'));
export const DoctorSearch = lazy(() => import('@/pages/DoctorSearch'));
export const LiveOrderTracking = lazy(() => import('@/pages/LiveOrderTracking'));
export const VirtualOrderTracking = lazy(() => import('@/pages/VirtualOrderTracking'));
export const DeliveryAgentTracker = lazy(() => import('@/pages/DeliveryAgentTracker'));
export const PhlebotomistTracker = lazy(() => import('@/pages/PhlebotomistTracker'));
export const ReturnRefundPolicy = lazy(() => import('@/pages/ReturnRefundPolicy'));
export const LabReportViewer = lazy(() => import('@/pages/LabReportViewer'));
export const ReferralProgram = lazy(() => import('@/pages/ReferralProgram'));
export const SymptomChecker = lazy(() => import('@/pages/SymptomChecker'));
export const TeleconsultPage = lazy(() => import('@/pages/TeleconsultPage'));
export const RatingPage = lazy(() => import('@/pages/RatingPage'));
export const MyCura = lazy(() => import('@/pages/MyCura'));
export const Portals = lazy(() => import('@/pages/Portals'));
export const PrescriptionScannerPage = lazy(() => import('@/pages/PrescriptionScannerPage'));
export const MyPrescriptions = lazy(() => import('@/pages/MyPrescriptions'));
export const VoiceBookingPage = lazy(() => import('@/pages/VoiceBookingPage'));
export const MedicineRemindersPage = lazy(() => import('@/pages/MedicineRemindersPage'));
export const FamilyHealthPage = lazy(() => import('@/pages/FamilyHealthPage'));
export const OrganViewerPage = lazy(() => import('@/pages/OrganViewerPage'));
export const BookingAnalyticsPage = lazy(() => import('@/pages/BookingAnalyticsPage'));
export const CuraCoinsPage = lazy(() => import('@/pages/CuraCoinsPage'));
export const HealthScorePage = lazy(() => import('@/pages/HealthScorePage'));
export const DoctorInsightsPage = lazy(() => import('@/pages/DoctorInsightsPage'));
export const EmergencySOSPage = lazy(() => import('@/pages/EmergencySOSPage'));
export const PaymentSuccess = lazy(() => import('@/pages/PaymentSuccess'));
export const ABHAPage = lazy(() => import('@/pages/ABHAPage'));
export const HealthAssistantPage = lazy(() => import('@/pages/HealthAssistantPage'));
export const CuraPlusPage = lazy(() => import('@/pages/CuraPlusPage'));
export const HyperlocalPage = lazy(() => import('@/pages/HyperlocalPage'));
export const VideoConsultPage = lazy(() => import('@/pages/VideoConsultPage'));
export const HealthStreaksPage = lazy(() => import('@/pages/HealthStreaksPage'));
export const WearablesPage = lazy(() => import('@/pages/WearablesPage'));
export const MedicalRecordsPage = lazy(() => import('@/pages/MedicalRecordsPage'));
export const SmartRemindersPage = lazy(() => import('@/pages/SmartRemindersPage'));
export const RevenueDashboard = lazy(() => import('@/pages/RevenueDashboard'));
export const HandoffNotes = lazy(() => import('@/pages/HandoffNotes'));
export const EmergencyHealthCard = lazy(() => import('@/pages/EmergencyHealthCard'));
export const EmergencyScanPage = lazy(() => import('@/pages/EmergencyScanPage'));
export const ExpressRxTracker = lazy(() => import('@/pages/ExpressRxTracker'));
export const PostVisitPipeline = lazy(() => import('@/pages/PostVisitPipeline'));
export const AdultVaccination = lazy(() => import('@/pages/AdultVaccination'));
export const HomeCare = lazy(() => import('@/pages/HomeCare'));
export const Evercare = lazy(() => import('@/pages/Evercare'));

// Lazy with retry
export const NotificationBanner = retryLazy(() => import('@/components/NotificationBanner'));
export const OnboardingTour = retryLazy(() => import('@/components/OnboardingTour'));

// Payment inline
export { PaymentCancel } from '@/components/PaymentCheckout';
