import React, { createContext, useContext, useState, useEffect } from 'react';

// Available languages
const LANGUAGES = {
  en: { code: 'en', name: 'English', nativeName: 'English' },
  hi: { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  mr: { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  gu: { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  ta: { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  te: { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  bho: { code: 'bho', name: 'Bhojpuri', nativeName: 'भोजपुरी' },
  mai: { code: 'mai', name: 'Maithili', nativeName: 'मैथिली' }
};

// Translations
const TRANSLATIONS = {
  en: {
    welcome: "Welcome to Nevika Cura",
    bookAppointment: "Book Appointment",
    orderMedicines: "Order Medicines",
    labTests: "Lab Tests",
    myHealth: "My Health",
    profile: "Profile",
    logout: "Logout",
    home: "Home",
    appointments: "Appointments",
    pharmacy: "Pharmacy",
    diagnostics: "Diagnostics",
    settings: "Settings",
    language: "Language",
    notifications: "Notifications",
    familyMembers: "Family Members",
    healthDashboard: "Health Dashboard",
    achievements: "Achievements",
    viewAll: "View All",
    save: "Save",
    cancel: "Cancel",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    loading: "Loading...",
    noData: "No data available",
    success: "Success",
    error: "Error",
    healthScore: "Health Score",
    logMetric: "Log Metric",
    weight: "Weight",
    bloodPressure: "Blood Pressure",
    heartRate: "Heart Rate",
    steps: "Steps",
    streak: "Streak",
    days: "days",
    addFamilyMember: "Add Family Member",
    relation: "Relation",
    self: "Self",
    spouse: "Spouse",
    child: "Child",
    parent: "Parent",
    sibling: "Sibling",
    other: "Other",
    notificationSettings: "Notification Settings",
    appointmentReminders: "Appointment Reminders",
    medicineRefill: "Medicine Refill Alerts",
    labResults: "Lab Results",
    promotional: "Promotional Messages",
    findDoctors: "Find Doctors",
    trackOrder: "Track Order",
    labReports: "Lab Reports",
    referEarn: "Refer & Earn",
    symptomChecker: "Symptom Checker",
    teleconsultation: "Teleconsultation",
    searchDoctor: "Search by name, specialty...",
    availableNow: "Available Now",
    bookNow: "Book Now",
    yourReferralCode: "Your Referral Code",
    shareWithFriends: "Share with Friends",
    dailyReward: "Daily Reward",
    howItWorks: "How it Works",
    analyzeSymptoms: "Analyze Symptoms",
    whereDoesItHurt: "Where does it hurt?",
    selectSymptoms: "Select your symptoms",
    severity: "Severity",
    videoConsult: "Video Consult",
    joinCall: "Join Consultation",
    abhaHealthId: "ABHA Health ID",
    mentalHealth: "Mental Health",
    healthStreaks: "Health Streaks",
    subscriptions: "Subscriptions",
    nearbyServices: "Nearby Services",
    videoCall: "Video Call",
    chat: "Chat",
    prescription: "Prescription",
    report: "Report",
    medicines: "Medicines",
    tests: "Tests",
    doctors: "Doctors",
    hospitals: "Hospitals",
    emergency: "Emergency",
    ambulance: "Ambulance",
    bloodBank: "Blood Bank",
    insurance: "Insurance",
    wallet: "Wallet",
    rewards: "Rewards",
    history: "History",
    today: "Today",
    tomorrow: "Tomorrow",
    morning: "Morning",
    evening: "Evening",
    selectDate: "Select Date",
    selectTime: "Select Time",
    payNow: "Pay Now",
    payLater: "Pay Later",
    cashOnDelivery: "Cash on Delivery",
    onlinePayment: "Online Payment",
    orderPlaced: "Order Placed",
    orderConfirmed: "Order Confirmed",
    outForDelivery: "Out for Delivery",
    delivered: "Delivered",
    searchMedicines: "Search medicines...",
    addToCart: "Add to Cart",
    removeFromCart: "Remove from Cart",
    viewCart: "View Cart",
    checkout: "Checkout",
    totalAmount: "Total Amount",
    discount: "Discount",
    deliveryCharges: "Delivery Charges",
    freeDelivery: "Free Delivery",
    estimatedDelivery: "Estimated Delivery",
    address: "Address",
    changeAddress: "Change Address",
    addAddress: "Add Address",
    savedAddresses: "Saved Addresses",
  },
  hi: {
    welcome: "नेविका कुरा में आपका स्वागत है",
    bookAppointment: "अपॉइंटमेंट बुक करें",
    orderMedicines: "दवाइयाँ ऑर्डर करें",
    labTests: "लैब टेस्ट",
    myHealth: "मेरा स्वास्थ्य",
    profile: "प्रोफ़ाइल",
    logout: "लॉग आउट",
    home: "होम",
    appointments: "अपॉइंटमेंट्स",
    pharmacy: "फार्मेसी",
    diagnostics: "डायग्नोस्टिक्स",
    settings: "सेटिंग्स",
    language: "भाषा",
    notifications: "सूचनाएं",
    familyMembers: "परिवार के सदस्य",
    healthDashboard: "स्वास्थ्य डैशबोर्ड",
    achievements: "उपलब्धियां",
    viewAll: "सभी देखें",
    save: "सेव करें",
    cancel: "रद्द करें",
    add: "जोड़ें",
    edit: "संपादित करें",
    delete: "हटाएं",
    confirm: "पुष्टि करें",
    loading: "लोड हो रहा है...",
    noData: "कोई डेटा उपलब्ध नहीं",
    success: "सफल",
    error: "त्रुटि",
    healthScore: "स्वास्थ्य स्कोर",
    logMetric: "मेट्रिक लॉग करें",
    weight: "वजन",
    bloodPressure: "रक्तचाप",
    heartRate: "हृदय गति",
    steps: "कदम",
    streak: "स्ट्रीक",
    days: "दिन",
    addFamilyMember: "परिवार का सदस्य जोड़ें",
    relation: "संबंध",
    self: "स्वयं",
    spouse: "पति/पत्नी",
    child: "बच्चा",
    parent: "माता-पिता",
    sibling: "भाई-बहन",
    other: "अन्य",
    notificationSettings: "सूचना सेटिंग्स",
    appointmentReminders: "अपॉइंटमेंट रिमाइंडर",
    medicineRefill: "दवा रिफिल अलर्ट",
    labResults: "लैब रिजल्ट्स",
    promotional: "प्रमोशनल मैसेज",
    findDoctors: "डॉक्टर खोजें",
    trackOrder: "ऑर्डर ट्रैक करें",
    labReports: "लैब रिपोर्ट",
    referEarn: "रेफ़र करें और कमाएं",
    symptomChecker: "लक्षण जांच",
    teleconsultation: "टेलीकंसल्टेशन",
    searchDoctor: "नाम, विशेषज्ञता से खोजें...",
    availableNow: "अभी उपलब्ध",
    bookNow: "अभी बुक करें",
    yourReferralCode: "आपका रेफ़रल कोड",
    shareWithFriends: "दोस्तों के साथ शेयर करें",
    dailyReward: "दैनिक इनाम",
    howItWorks: "कैसे काम करता है",
    analyzeSymptoms: "लक्षणों का विश्लेषण करें",
    whereDoesItHurt: "कहाँ दर्द है?",
    selectSymptoms: "अपने लक्षण चुनें",
    severity: "गंभीरता",
    videoConsult: "वीडियो कंसल्ट",
    joinCall: "कंसल्टेशन जॉइन करें",
    abhaHealthId: "ABHA स्वास्थ्य आईडी",
    mentalHealth: "मानसिक स्वास्थ्य",
    healthStreaks: "स्वास्थ्य स्ट्रीक्स",
    subscriptions: "सदस्यता",
    nearbyServices: "आस-पास की सेवाएं",
    videoCall: "वीडियो कॉल",
    chat: "चैट",
    prescription: "प्रिस्क्रिप्शन",
    report: "रिपोर्ट",
    medicines: "दवाइयाँ",
    tests: "टेस्ट",
    doctors: "डॉक्टर",
    hospitals: "अस्पताल",
    emergency: "आपातकाल",
    ambulance: "एम्बुलेंस",
    bloodBank: "ब्लड बैंक",
    insurance: "बीमा",
    wallet: "वॉलेट",
    rewards: "रिवॉर्ड्स",
    history: "इतिहास",
    today: "आज",
    tomorrow: "कल",
    morning: "सुबह",
    evening: "शाम",
    selectDate: "तारीख चुनें",
    selectTime: "समय चुनें",
    payNow: "अभी भुगतान करें",
    payLater: "बाद में भुगतान करें",
    cashOnDelivery: "कैश ऑन डिलीवरी",
    onlinePayment: "ऑनलाइन भुगतान",
    orderPlaced: "ऑर्डर हो गया",
    orderConfirmed: "ऑर्डर कन्फर्म",
    outForDelivery: "डिलीवरी पर",
    delivered: "डिलीवर हो गया",
    searchMedicines: "दवाइयाँ खोजें...",
    addToCart: "कार्ट में जोड़ें",
    removeFromCart: "कार्ट से हटाएं",
    viewCart: "कार्ट देखें",
    checkout: "चेकआउट",
    totalAmount: "कुल राशि",
    discount: "छूट",
    deliveryCharges: "डिलीवरी शुल्क",
    freeDelivery: "मुफ्त डिलीवरी",
    estimatedDelivery: "अनुमानित डिलीवरी",
    address: "पता",
    changeAddress: "पता बदलें",
    addAddress: "पता जोड़ें",
    savedAddresses: "सेव किए गए पते",
  },
  mr: {
    welcome: "नेविका कुरा मध्ये आपले स्वागत आहे",
    bookAppointment: "अपॉइंटमेंट बुक करा",
    orderMedicines: "औषधे ऑर्डर करा",
    labTests: "लॅब चाचण्या",
    myHealth: "माझे आरोग्य",
    profile: "प्रोफाइल",
    logout: "लॉग आउट",
    home: "होम",
    appointments: "अपॉइंटमेंट्स",
    pharmacy: "फार्मसी",
    diagnostics: "डायग्नोस्टिक्स",
    settings: "सेटिंग्ज",
    language: "भाषा",
    notifications: "सूचना",
    familyMembers: "कुटुंबातील सदस्य",
    healthDashboard: "आरोग्य डॅशबोर्ड",
    achievements: "उपलब्धी",
    viewAll: "सर्व पहा",
    save: "जतन करा",
    cancel: "रद्द करा",
    add: "जोडा",
    edit: "संपादित करा",
    delete: "हटवा",
    confirm: "पुष्टी करा",
    loading: "लोड होत आहे...",
    noData: "डेटा उपलब्ध नाही",
    success: "यशस्वी",
    error: "त्रुटी",
    healthScore: "आरोग्य स्कोअर",
    logMetric: "मेट्रिक लॉग करा",
    weight: "वजन",
    bloodPressure: "रक्तदाब",
    heartRate: "हृदय गती",
    steps: "पावले",
    streak: "स्ट्रीक",
    days: "दिवस",
    addFamilyMember: "कुटुंबातील सदस्य जोडा",
    relation: "नाते",
    self: "स्वतः",
    spouse: "जोडीदार",
    child: "मूल",
    parent: "पालक",
    sibling: "भाऊ-बहीण",
    other: "इतर",
    notificationSettings: "सूचना सेटिंग्ज",
    appointmentReminders: "अपॉइंटमेंट रिमाइंडर",
    medicineRefill: "औषध रिफिल अलर्ट",
    labResults: "लॅब रिझल्ट्स",
    promotional: "प्रमोशनल मेसेज",
    findDoctors: "डॉक्टर शोधा",
    trackOrder: "ऑर्डर ट्रॅक करा",
    labReports: "लॅब रिपोर्ट",
    referEarn: "रेफर करा आणि कमवा",
    symptomChecker: "लक्षणे तपासा",
    teleconsultation: "टेलीकन्सल्टेशन",
    searchDoctor: "नाव, विशेषज्ञतेने शोधा...",
    availableNow: "आता उपलब्ध",
    bookNow: "आता बुक करा",
    yourReferralCode: "तुमचा रेफरल कोड",
    shareWithFriends: "मित्रांसोबत शेअर करा",
    dailyReward: "दैनिक बक्षीस",
    howItWorks: "कसे काम करते",
    analyzeSymptoms: "लक्षणांचे विश्लेषण करा",
    whereDoesItHurt: "कुठे दुखतंय?",
    selectSymptoms: "तुमची लक्षणे निवडा",
    severity: "तीव्रता",
    videoConsult: "व्हिडिओ कन्सल्ट",
    joinCall: "कन्सल्टेशनमध्ये सामील व्हा",
    abhaHealthId: "ABHA आरोग्य आयडी",
    mentalHealth: "मानसिक आरोग्य",
    healthStreaks: "आरोग्य स्ट्रीक्स",
    subscriptions: "सदस्यत्व",
    nearbyServices: "जवळपासच्या सेवा",
    videoCall: "व्हिडिओ कॉल",
    chat: "चॅट",
    prescription: "प्रिस्क्रिप्शन",
    report: "रिपोर्ट",
    medicines: "औषधे",
    tests: "चाचण्या",
    doctors: "डॉक्टर",
    hospitals: "रुग्णालये",
    emergency: "आपत्कालीन",
    ambulance: "रुग्णवाहिका",
    bloodBank: "रक्तपेढी",
    insurance: "विमा",
    wallet: "वॉलेट",
    rewards: "बक्षिसे",
    history: "इतिहास",
    today: "आज",
    tomorrow: "उद्या",
    morning: "सकाळ",
    evening: "संध्याकाळ",
    selectDate: "तारीख निवडा",
    selectTime: "वेळ निवडा",
    payNow: "आता पैसे द्या",
    payLater: "नंतर पैसे द्या",
    cashOnDelivery: "डिलिव्हरीवर पैसे",
    onlinePayment: "ऑनलाइन पेमेंट",
    orderPlaced: "ऑर्डर दिली",
    orderConfirmed: "ऑर्डर कन्फर्म",
    outForDelivery: "डिलिव्हरीसाठी बाहेर",
    delivered: "डिलिव्हर झाले",
    searchMedicines: "औषधे शोधा...",
    addToCart: "कार्टमध्ये जोडा",
    removeFromCart: "कार्टमधून काढा",
    viewCart: "कार्ट पहा",
    checkout: "चेकआउट",
    totalAmount: "एकूण रक्कम",
    discount: "सूट",
    deliveryCharges: "डिलिव्हरी शुल्क",
    freeDelivery: "मोफत डिलिव्हरी",
    estimatedDelivery: "अंदाजे डिलिव्हरी",
    address: "पत्ता",
    changeAddress: "पत्ता बदला",
    addAddress: "पत्ता जोडा",
    savedAddresses: "जतन केलेले पत्ते",
  },
  gu: {
    welcome: "નેવિકા કુરા માં આપનું સ્વાગત છે",
    bookAppointment: "એપોઇન્ટમેન્ટ બુક કરો",
    orderMedicines: "દવાઓ ઓર્ડર કરો",
    labTests: "લેબ ટેસ્ટ",
    myHealth: "મારું સ્વાસ્થ્ય",
    profile: "પ્રોફાઇલ",
    logout: "લૉગ આઉટ",
    home: "હોમ",
    appointments: "એપોઇન્ટમેન્ટ્સ",
    pharmacy: "ફાર્મસી",
    diagnostics: "ડાયગ્નોસ્ટિક્સ",
    settings: "સેટિંગ્સ",
    language: "ભાષા",
    notifications: "સૂચનાઓ",
    familyMembers: "પરિવારના સભ્યો",
    healthDashboard: "સ્વાસ્થ્ય ડેશબોર્ડ",
    achievements: "સિદ્ધિઓ",
    viewAll: "બધું જુઓ",
    save: "સેવ કરો",
    cancel: "રદ કરો",
    add: "ઉમેરો",
    edit: "સંપાદિત કરો",
    delete: "કાઢી નાખો",
    confirm: "ખાતરી કરો",
    loading: "લોડ થઈ રહ્યું છે...",
    noData: "કોઈ ડેટા ઉપલબ્ધ નથી",
    success: "સફળ",
    error: "ભૂલ",
    healthScore: "સ્વાસ્થ્ય સ્કોર",
    logMetric: "મેટ્રિક લૉગ કરો",
    weight: "વજન",
    bloodPressure: "બ્લડ પ્રેશર",
    heartRate: "હૃદય ગતિ",
    steps: "પગલાં",
    streak: "સ્ટ્રીક",
    days: "દિવસ",
    addFamilyMember: "પરિવારનો સભ્ય ઉમેરો",
    relation: "સંબંધ",
    self: "પોતે",
    spouse: "પતિ/પત્ની",
    child: "બાળક",
    parent: "માતા-પિતા",
    sibling: "ભાઈ-બહેન",
    other: "અન્ય",
    notificationSettings: "સૂચના સેટિંગ્સ",
    appointmentReminders: "એપોઇન્ટમેન્ટ રિમાઇન્ડર",
    medicineRefill: "દવા રિફિલ એલર્ટ",
    labResults: "લેબ રિઝલ્ટ્સ",
    promotional: "પ્રમોશનલ મેસેજ",
    findDoctors: "ડૉક્ટર શોધો",
    trackOrder: "ઓર્ડર ટ્રેક કરો",
    labReports: "લેબ રિપોર્ટ",
    referEarn: "રેફર કરો અને કમાઓ",
    symptomChecker: "લક્ષણ તપાસ",
    teleconsultation: "ટેલીકન્સલ્ટેશન",
    searchDoctor: "નામ, વિશેષજ્ઞતા દ્વારા શોધો...",
    availableNow: "હવે ઉપલબ્ધ",
    bookNow: "હવે બુક કરો",
    yourReferralCode: "તમારો રેફરલ કોડ",
    shareWithFriends: "મિત્રો સાથે શેર કરો",
    dailyReward: "દૈનિક ઇનામ",
    howItWorks: "કેવી રીતે કામ કરે છે",
    analyzeSymptoms: "લક્ષણોનું વિશ્લેષણ કરો",
    whereDoesItHurt: "ક્યાં દુખે છે?",
    selectSymptoms: "તમારા લક્ષણો પસંદ કરો",
    severity: "ગંભીરતા",
    videoConsult: "વીડિયો કન્સલ્ટ",
    joinCall: "કન્સલ્ટેશનમાં જોડાઓ",
    abhaHealthId: "ABHA સ્વાસ્થ્ય આઈડી",
    mentalHealth: "માનસિક સ્વાસ્થ્ય",
    healthStreaks: "સ્વાસ્થ્ય સ્ટ્રીક્સ",
    subscriptions: "સબ્સ્ક્રિપ્શન",
    nearbyServices: "નજીકની સેવાઓ",
    videoCall: "વીડિયો કૉલ",
    chat: "ચેટ",
    prescription: "પ્રિસ્ક્રિપ્શન",
    report: "રિપોર્ટ",
    medicines: "દવાઓ",
    tests: "ટેસ્ટ",
    doctors: "ડૉક્ટર",
    hospitals: "હોસ્પિટલ",
    emergency: "ઇમર્જન્સી",
    ambulance: "એમ્બ્યુલન્સ",
    bloodBank: "બ્લડ બેંક",
    insurance: "વીમો",
    wallet: "વૉલેટ",
    rewards: "રિવૉર્ડ્સ",
    history: "ઇતિહાસ",
    today: "આજે",
    tomorrow: "આવતીકાલે",
    morning: "સવારે",
    evening: "સાંજે",
    selectDate: "તારીખ પસંદ કરો",
    selectTime: "સમય પસંદ કરો",
    payNow: "હવે ચૂકવો",
    payLater: "પછીથી ચૂકવો",
    cashOnDelivery: "કેશ ઓન ડિલિવરી",
    onlinePayment: "ઓનલાઇન પેમેન્ટ",
    orderPlaced: "ઓર્ડર મૂક્યો",
    orderConfirmed: "ઓર્ડર કન્ફર્મ",
    outForDelivery: "ડિલિવરી માટે નીકળ્યો",
    delivered: "ડિલિવર થયો",
    searchMedicines: "દવાઓ શોધો...",
    addToCart: "કાર્ટમાં ઉમેરો",
    removeFromCart: "કાર્ટમાંથી કાઢો",
    viewCart: "કાર્ટ જુઓ",
    checkout: "ચેકઆઉટ",
    totalAmount: "કુલ રકમ",
    discount: "ડિસ્કાઉન્ટ",
    deliveryCharges: "ડિલિવરી ચાર્જ",
    freeDelivery: "મફત ડિલિવરી",
    estimatedDelivery: "અંદાજિત ડિલિવરી",
    address: "સરનામું",
    changeAddress: "સરનામું બદલો",
    addAddress: "સરનામું ઉમેરો",
    savedAddresses: "સેવ કરેલા સરનામાં",
  },
  ta: {
    welcome: "நெவிகா குரா-வுக்கு வரவேற்கிறோம்",
    bookAppointment: "முன்பதிவு செய்யுங்கள்",
    orderMedicines: "மருந்துகள் ஆர்டர் செய்யுங்கள்",
    labTests: "லேப் டெஸ்ட்",
    myHealth: "என் ஆரோக்கியம்",
    profile: "சுயவிவரம்",
    logout: "வெளியேறு",
    home: "முகப்பு",
    appointments: "சந்திப்புகள்",
    pharmacy: "மருந்தகம்",
    diagnostics: "கண்டறிதல்",
    settings: "அமைப்புகள்",
    language: "மொழி",
    notifications: "அறிவிப்புகள்",
    familyMembers: "குடும்ப உறுப்பினர்கள்",
    healthDashboard: "ஆரோக்கிய டாஷ்போர்டு",
    achievements: "சாதனைகள்",
    viewAll: "அனைத்தும் காண்க",
    save: "சேமி",
    cancel: "ரத்து செய்",
    add: "சேர்",
    edit: "திருத்து",
    delete: "நீக்கு",
    confirm: "உறுதிப்படுத்து",
    loading: "ஏற்றுகிறது...",
    noData: "தரவு இல்லை",
    success: "வெற்றி",
    error: "பிழை",
    healthScore: "ஆரோக்கிய மதிப்பெண்",
    logMetric: "அளவீடு பதிவு",
    weight: "எடை",
    bloodPressure: "இரத்த அழுத்தம்",
    heartRate: "இதய துடிப்பு",
    steps: "அடிகள்",
    streak: "தொடர்",
    days: "நாட்கள்",
    addFamilyMember: "குடும்ப உறுப்பினரைச் சேர்",
    relation: "உறவு",
    self: "சுயம்",
    spouse: "கணவர்/மனைவி",
    child: "குழந்தை",
    parent: "பெற்றோர்",
    sibling: "சகோதரர்/சகோதரி",
    other: "மற்றவை",
    notificationSettings: "அறிவிப்பு அமைப்புகள்",
    appointmentReminders: "சந்திப்பு நினைவூட்டல்",
    medicineRefill: "மருந்து ரீஃபில் எச்சரிக்கை",
    labResults: "லேப் முடிவுகள்",
    promotional: "விளம்பர செய்திகள்",
    findDoctors: "மருத்துவரைக் கண்டறியுங்கள்",
    trackOrder: "ஆர்டர் கண்காணி",
    labReports: "லேப் அறிக்கை",
    referEarn: "பரிந்துரை செய்து சம்பாதியுங்கள்",
    symptomChecker: "அறிகுறி சோதனை",
    teleconsultation: "டெலிகன்சல்டேஷன்",
    searchDoctor: "பெயர், நிபுணத்துவம் மூலம் தேடுங்கள்...",
    availableNow: "இப்போது கிடைக்கும்",
    bookNow: "இப்போது புக் செய்",
    yourReferralCode: "உங்கள் ரெஃபரல் கோட்",
    shareWithFriends: "நண்பர்களுடன் பகிரு",
    dailyReward: "தினசரி வெகுமதி",
    howItWorks: "இது எப்படி செயல்படுகிறது",
    analyzeSymptoms: "அறிகுறிகளை பகுப்பாய்வு செய்",
    whereDoesItHurt: "எங்கே வலிக்கிறது?",
    selectSymptoms: "உங்கள் அறிகுறிகளைத் தேர்ந்தெடுக்கவும்",
    severity: "தீவிரம்",
    videoConsult: "வீடியோ கன்சல்ட்",
    joinCall: "கன்சல்டேஷனில் சேரு",
    abhaHealthId: "ABHA ஆரோக்கிய அடையாளம்",
    mentalHealth: "மன ஆரோக்கியம்",
    healthStreaks: "ஆரோக்கிய தொடர்கள்",
    subscriptions: "சந்தாக்கள்",
    nearbyServices: "அருகிலுள்ள சேவைகள்",
    videoCall: "வீடியோ அழைப்பு",
    chat: "அரட்டை",
    prescription: "மருந்துச்சீட்டு",
    report: "அறிக்கை",
    medicines: "மருந்துகள்",
    tests: "சோதனைகள்",
    doctors: "மருத்துவர்கள்",
    hospitals: "மருத்துவமனைகள்",
    emergency: "அவசரம்",
    ambulance: "ஆம்புலன்ஸ்",
    bloodBank: "இரத்த வங்கி",
    insurance: "காப்பீடு",
    wallet: "வாலெட்",
    rewards: "வெகுமதிகள்",
    history: "வரலாறு",
    today: "இன்று",
    tomorrow: "நாளை",
    morning: "காலை",
    evening: "மாலை",
    selectDate: "தேதி தேர்ந்தெடு",
    selectTime: "நேரம் தேர்ந்தெடு",
    payNow: "இப்போது செலுத்து",
    payLater: "பின்னர் செலுத்து",
    cashOnDelivery: "கேஷ் ஆன் டெலிவரி",
    onlinePayment: "ஆன்லைன் பணம்",
    orderPlaced: "ஆர்டர் செய்யப்பட்டது",
    orderConfirmed: "ஆர்டர் உறுதி",
    outForDelivery: "டெலிவரிக்கு சென்றது",
    delivered: "டெலிவர் ஆனது",
    searchMedicines: "மருந்துகள் தேடு...",
    addToCart: "கார்ட்டில் சேர்",
    removeFromCart: "கார்ட்டிலிருந்து நீக்கு",
    viewCart: "கார்ட் பார்",
    checkout: "செக்அவுட்",
    totalAmount: "மொத்த தொகை",
    discount: "தள்ளுபடி",
    deliveryCharges: "டெலிவரி கட்டணம்",
    freeDelivery: "இலவச டெலிவரி",
    estimatedDelivery: "மதிப்பிட்ட டெலிவரி",
    address: "முகவரி",
    changeAddress: "முகவரி மாற்று",
    addAddress: "முகவரி சேர்",
    savedAddresses: "சேமித்த முகவரிகள்",
  },
  te: {
    welcome: "నెవికా కురా కు స్వాగతం",
    bookAppointment: "అపాయింట్‌మెంట్ బుక్ చేయండి",
    orderMedicines: "మందులు ఆర్డర్ చేయండి",
    labTests: "ల్యాబ్ టెస్ట్‌లు",
    myHealth: "నా ఆరోగ్యం",
    profile: "ప్రొఫైల్",
    logout: "లాగ్ అవుట్",
    home: "హోమ్",
    appointments: "అపాయింట్‌మెంట్‌లు",
    pharmacy: "ఫార్మసీ",
    diagnostics: "డయాగ్నోస్టిక్స్",
    settings: "సెట్టింగ్‌లు",
    language: "భాష",
    notifications: "నోటిఫికేషన్‌లు",
    familyMembers: "కుటుంబ సభ్యులు",
    healthDashboard: "ఆరోగ్య డాష్‌బోర్డ్",
    achievements: "విజయాలు",
    viewAll: "అన్నీ చూడండి",
    save: "సేవ్",
    cancel: "రద్దు",
    add: "జోడించు",
    edit: "సవరించు",
    delete: "తొలగించు",
    confirm: "నిర్ధారించు",
    loading: "లోడ్ అవుతోంది...",
    noData: "డేటా అందుబాటులో లేదు",
    success: "విజయం",
    error: "లోపం",
    healthScore: "ఆరోగ్య స్కోర్",
    logMetric: "మెట్రిక్ లాగ్",
    weight: "బరువు",
    bloodPressure: "రక్తపోటు",
    heartRate: "గుండె స్పందన",
    steps: "అడుగులు",
    streak: "స్ట్రీక్",
    days: "రోజులు",
    addFamilyMember: "కుటుంబ సభ్యుని జోడించు",
    relation: "సంబంధం",
    self: "స్వయం",
    spouse: "భాగస్వామి",
    child: "పిల్లలు",
    parent: "తల్లిదండ్రులు",
    sibling: "సోదరుడు/సోదరి",
    other: "ఇతరం",
    notificationSettings: "నోటిఫికేషన్ సెట్టింగ్‌లు",
    appointmentReminders: "అపాయింట్‌మెంట్ రిమైండర్‌లు",
    medicineRefill: "మందు రీఫిల్ అలర్ట్‌లు",
    labResults: "ల్యాబ్ ఫలితాలు",
    promotional: "ప్రమోషనల్ సందేశాలు",
    findDoctors: "డాక్టర్లను కనుగొనండి",
    trackOrder: "ఆర్డర్ ట్రాక్",
    labReports: "ల్యాబ్ రిపోర్ట్‌లు",
    referEarn: "రిఫర్ చేసి సంపాదించండి",
    symptomChecker: "లక్షణ తనిఖీ",
    teleconsultation: "టెలీకన్సల్టేషన్",
    searchDoctor: "పేరు, స్పెషాలిటీ ద్వారా శోధించండి...",
    availableNow: "ఇప్పుడు అందుబాటులో",
    bookNow: "ఇప్పుడు బుక్ చేయండి",
    yourReferralCode: "మీ రిఫరల్ కోడ్",
    shareWithFriends: "స్నేహితులతో షేర్ చేయండి",
    dailyReward: "రోజువారీ రివార్డ్",
    howItWorks: "ఇది ఎలా పని చేస్తుంది",
    analyzeSymptoms: "లక్షణాలను విశ్లేషించండి",
    whereDoesItHurt: "ఎక్కడ నొప్పిగా ఉంది?",
    selectSymptoms: "మీ లక్షణాలను ఎంచుకోండి",
    severity: "తీవ్రత",
    videoConsult: "వీడియో కన్సల్ట్",
    joinCall: "కన్సల్టేషన్‌లో చేరండి",
    abhaHealthId: "ABHA ఆరోగ్య ID",
    mentalHealth: "మానసిక ఆరోగ్యం",
    healthStreaks: "ఆరోగ్య స్ట్రీక్‌లు",
    subscriptions: "సబ్‌స్క్రిప్షన్‌లు",
    nearbyServices: "సమీపంలోని సేవలు",
    videoCall: "వీడియో కాల్",
    chat: "చాట్",
    prescription: "ప్రిస్క్రిప్షన్",
    report: "రిపోర్ట్",
    medicines: "మందులు",
    tests: "పరీక్షలు",
    doctors: "వైద్యులు",
    hospitals: "ఆసుపత్రులు",
    emergency: "అత్యవసరం",
    ambulance: "అంబులెన్స్",
    bloodBank: "రక్తనిధి",
    insurance: "బీమా",
    wallet: "వాలెట్",
    rewards: "రివార్డ్‌లు",
    history: "చరిత్ర",
    today: "ఈరోజు",
    tomorrow: "రేపు",
    morning: "ఉదయం",
    evening: "సాయంత్రం",
    selectDate: "తేదీ ఎంచుకోండి",
    selectTime: "సమయం ఎంచుకోండి",
    payNow: "ఇప్పుడు చెల్లించండి",
    payLater: "తర్వాత చెల్లించండి",
    cashOnDelivery: "క్యాష్ ఆన్ డెలివరీ",
    onlinePayment: "ఆన్‌లైన్ చెల్లింపు",
    orderPlaced: "ఆర్డర్ చేయబడింది",
    orderConfirmed: "ఆర్డర్ నిర్ధారించబడింది",
    outForDelivery: "డెలివరీకి బయలుదేరింది",
    delivered: "డెలివరీ అయింది",
    searchMedicines: "మందులు శోధించండి...",
    addToCart: "కార్ట్‌కి జోడించు",
    removeFromCart: "కార్ట్ నుండి తొలగించు",
    viewCart: "కార్ట్ చూడు",
    checkout: "చెకౌట్",
    totalAmount: "మొత్తం మొత్తం",
    discount: "తగ్గింపు",
    deliveryCharges: "డెలివరీ ఛార్జీలు",
    freeDelivery: "ఉచిత డెలివరీ",
    estimatedDelivery: "అంచనా డెలివరీ",
    address: "చిరునామా",
    changeAddress: "చిరునామా మార్చు",
    addAddress: "చిరునామా జోడించు",
    savedAddresses: "సేవ్ చేసిన చిరునామాలు",
  },
  bho: {
    welcome: "नेविका कुरा में रउआ के स्वागत बा",
    bookAppointment: "अपॉइंटमेंट बुक करीं",
    orderMedicines: "दवाई मँगाईं",
    labTests: "लैब टेस्ट",
    myHealth: "हमार स्वास्थ्य",
    profile: "प्रोफ़ाइल",
    logout: "लॉग आउट",
    home: "होम",
    appointments: "अपॉइंटमेंट",
    pharmacy: "दवाखाना",
    diagnostics: "जाँच",
    settings: "सेटिंग",
    language: "भाषा",
    notifications: "सूचना",
    familyMembers: "परिवार के लोग",
    healthDashboard: "स्वास्थ्य डैशबोर्ड",
    achievements: "उपलब्धि",
    viewAll: "सब देखीं",
    save: "सेव करीं",
    cancel: "रद्द करीं",
    add: "जोड़ीं",
    edit: "बदलीं",
    delete: "हटाईं",
    confirm: "पक्का करीं",
    loading: "लोड हो रहल बा...",
    noData: "कवनो डेटा नइखे",
    success: "सफल",
    error: "गलती",
    healthScore: "स्वास्थ्य स्कोर",
    logMetric: "मेट्रिक लॉग करीं",
    weight: "वजन",
    bloodPressure: "ब्लड प्रेशर",
    heartRate: "दिल के धड़कन",
    steps: "कदम",
    streak: "लगातार",
    days: "दिन",
    addFamilyMember: "परिवार के सदस्य जोड़ीं",
    relation: "रिश्ता",
    self: "खुद",
    spouse: "पति/पत्नी",
    child: "बच्चा",
    parent: "माई-बाबू",
    sibling: "भाई-बहिन",
    other: "अउर",
    notificationSettings: "सूचना सेटिंग",
    appointmentReminders: "अपॉइंटमेंट रिमाइंडर",
    medicineRefill: "दवाई रिफिल अलर्ट",
    labResults: "लैब रिजल्ट",
    promotional: "प्रमोशनल मैसेज",
    findDoctors: "डॉक्टर खोजीं",
    trackOrder: "ऑर्डर ट्रैक करीं",
    labReports: "लैब रिपोर्ट",
    referEarn: "रेफ़र करीं आ कमाईं",
    symptomChecker: "लक्षण जाँच",
    teleconsultation: "वीडियो सलाह",
    searchDoctor: "नाम, विशेषज्ञता से खोजीं...",
    availableNow: "अभी उपलब्ध बा",
    bookNow: "अभी बुक करीं",
    yourReferralCode: "रउआ के रेफ़रल कोड",
    shareWithFriends: "दोस्तन के साथ शेयर करीं",
    dailyReward: "रोज के इनाम",
    howItWorks: "कइसे काम करेला",
    analyzeSymptoms: "लक्षणन के जाँच करीं",
    whereDoesItHurt: "कहवाँ दरद बा?",
    selectSymptoms: "आपन लक्षण चुनीं",
    severity: "कतना तेज",
    videoConsult: "वीडियो कंसल्ट",
    joinCall: "कॉल में शामिल होईं",
    abhaHealthId: "ABHA स्वास्थ्य आईडी",
    mentalHealth: "मानसिक स्वास्थ्य",
    healthStreaks: "स्वास्थ्य स्ट्रीक",
    subscriptions: "सदस्यता",
    nearbyServices: "आस-पास के सेवा",
    videoCall: "वीडियो कॉल",
    chat: "चैट",
    prescription: "दवाई पर्ची",
    report: "रिपोर्ट",
    medicines: "दवाई",
    tests: "टेस्ट",
    doctors: "डॉक्टर",
    hospitals: "अस्पताल",
    emergency: "आपातकाल",
    ambulance: "एम्बुलेंस",
    bloodBank: "ब्लड बैंक",
    insurance: "बीमा",
    wallet: "वॉलेट",
    rewards: "इनाम",
    history: "इतिहास",
    today: "आज",
    tomorrow: "काल्ह",
    morning: "भिनसरे",
    evening: "साँझ",
    selectDate: "तारीख चुनीं",
    selectTime: "समय चुनीं",
    payNow: "अभी पैसा दीं",
    payLater: "बाद में पैसा दीं",
    cashOnDelivery: "डिलीवरी पर पैसा",
    onlinePayment: "ऑनलाइन पेमेंट",
    orderPlaced: "ऑर्डर हो गइल",
    orderConfirmed: "ऑर्डर कन्फर्म",
    outForDelivery: "डिलीवरी पर निकलल",
    delivered: "पहुँच गइल",
    searchMedicines: "दवाई खोजीं...",
    addToCart: "कार्ट में जोड़ीं",
    removeFromCart: "कार्ट से हटाईं",
    viewCart: "कार्ट देखीं",
    checkout: "चेकआउट",
    totalAmount: "कुल रकम",
    discount: "छूट",
    deliveryCharges: "डिलीवरी चार्ज",
    freeDelivery: "मुफ्त डिलीवरी",
    estimatedDelivery: "अनुमानित डिलीवरी",
    address: "पता",
    changeAddress: "पता बदलीं",
    addAddress: "पता जोड़ीं",
    savedAddresses: "सेव कइल पता",
  },
  mai: {
    welcome: "नेविका कुरा मे अहाँक स्वागत अछि",
    bookAppointment: "अपॉइंटमेंट बुक करू",
    orderMedicines: "दवाइ मँगाउ",
    labTests: "लैब टेस्ट",
    myHealth: "हमर स्वास्थ्य",
    profile: "प्रोफ़ाइल",
    logout: "लॉग आउट",
    home: "होम",
    appointments: "अपॉइंटमेंट",
    pharmacy: "दवाखाना",
    diagnostics: "जाँच",
    settings: "सेटिंग",
    language: "भाषा",
    notifications: "सूचना",
    familyMembers: "परिवार केर सदस्य",
    healthDashboard: "स्वास्थ्य डैशबोर्ड",
    achievements: "उपलब्धि",
    viewAll: "सभ देखू",
    save: "सेव करू",
    cancel: "रद्द करू",
    add: "जोड़ू",
    edit: "बदलू",
    delete: "हटाउ",
    confirm: "पक्का करू",
    loading: "लोड भ रहल अछि...",
    noData: "कोनो डेटा नहि अछि",
    success: "सफल",
    error: "गलती",
    healthScore: "स्वास्थ्य स्कोर",
    logMetric: "मेट्रिक लॉग करू",
    weight: "वजन",
    bloodPressure: "रक्तचाप",
    heartRate: "हृदय गति",
    steps: "कदम",
    streak: "लगातार",
    days: "दिन",
    addFamilyMember: "परिवार केर सदस्य जोड़ू",
    relation: "रिश्ता",
    self: "अपने",
    spouse: "पति/पत्नी",
    child: "बच्चा",
    parent: "माय-बाबू",
    sibling: "भाय-बहिन",
    other: "आओर",
    notificationSettings: "सूचना सेटिंग",
    appointmentReminders: "अपॉइंटमेंट रिमाइंडर",
    medicineRefill: "दवाइ रिफिल अलर्ट",
    labResults: "लैब रिजल्ट",
    promotional: "प्रमोशनल मैसेज",
    findDoctors: "डॉक्टर खोजू",
    trackOrder: "ऑर्डर ट्रैक करू",
    labReports: "लैब रिपोर्ट",
    referEarn: "रेफ़र करू आ कमाउ",
    symptomChecker: "लक्षण जाँच",
    teleconsultation: "वीडियो सलाह",
    searchDoctor: "नाम, विशेषज्ञता सँ खोजू...",
    availableNow: "एखन उपलब्ध अछि",
    bookNow: "एखन बुक करू",
    yourReferralCode: "अहाँक रेफ़रल कोड",
    shareWithFriends: "मित्र संग शेयर करू",
    dailyReward: "दैनिक इनाम",
    howItWorks: "कोना काज करैत अछि",
    analyzeSymptoms: "लक्षणक जाँच करू",
    whereDoesItHurt: "कतय दरद अछि?",
    selectSymptoms: "अपन लक्षण चुनू",
    severity: "कतेक तेज",
    videoConsult: "वीडियो कंसल्ट",
    joinCall: "कॉल मे शामिल होउ",
    abhaHealthId: "ABHA स्वास्थ्य आईडी",
    mentalHealth: "मानसिक स्वास्थ्य",
    healthStreaks: "स्वास्थ्य स्ट्रीक",
    subscriptions: "सदस्यता",
    nearbyServices: "लग-पासक सेवा",
    videoCall: "वीडियो कॉल",
    chat: "चैट",
    prescription: "दवाइ पर्ची",
    report: "रिपोर्ट",
    medicines: "दवाइ",
    tests: "टेस्ट",
    doctors: "डॉक्टर",
    hospitals: "अस्पताल",
    emergency: "आपातकाल",
    ambulance: "एम्बुलेंस",
    bloodBank: "रक्तदान केंद्र",
    insurance: "बीमा",
    wallet: "वॉलेट",
    rewards: "इनाम",
    history: "इतिहास",
    today: "आइ",
    tomorrow: "काल्हि",
    morning: "भोर",
    evening: "साँझ",
    selectDate: "तारीख चुनू",
    selectTime: "समय चुनू",
    payNow: "एखन पैसा दिअ",
    payLater: "बाद मे पैसा दिअ",
    cashOnDelivery: "डिलीवरी पर पैसा",
    onlinePayment: "ऑनलाइन पेमेंट",
    orderPlaced: "ऑर्डर भ गेल",
    orderConfirmed: "ऑर्डर कन्फर्म",
    outForDelivery: "डिलीवरी लेल निकलल",
    delivered: "पहुँच गेल",
    searchMedicines: "दवाइ खोजू...",
    addToCart: "कार्ट मे जोड़ू",
    removeFromCart: "कार्ट सँ हटाउ",
    viewCart: "कार्ट देखू",
    checkout: "चेकआउट",
    totalAmount: "कुल रकम",
    discount: "छूट",
    deliveryCharges: "डिलीवरी चार्ज",
    freeDelivery: "मुफ्त डिलीवरी",
    estimatedDelivery: "अनुमानित डिलीवरी",
    address: "पता",
    changeAddress: "पता बदलू",
    addAddress: "पता जोड़ू",
    savedAddresses: "सेव कयल पता",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('nevika_language');
    if (saved && LANGUAGES[saved]) return saved;
    
    // Auto-detect based on browser language
    const browserLang = navigator.language || navigator.userLanguage || '';
    if (browserLang.startsWith('hi')) return 'hi';
    if (browserLang.startsWith('mr')) return 'mr';
    if (browserLang.startsWith('gu')) return 'gu';
    if (browserLang.startsWith('ta')) return 'ta';
    if (browserLang.startsWith('te')) return 'te';
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem('nevika_language', language);
  }, [language]);

  const t = (key) => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key;
  };

  const changeLanguage = (newLang) => {
    if (LANGUAGES[newLang]) {
      setLanguage(newLang);
    }
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage: changeLanguage, 
      t, 
      languages: LANGUAGES,
      isRTL: false
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export { LANGUAGES, TRANSLATIONS };
