// AI-generated comprehensive test details for Mango Health Labs
// Each test has: description, sampleType, fasting, reportTime, parameters, category

const TEST_DETAILS_MAP = {
  // ===== BLOOD TESTS - GENERAL =====
  'CBC (Complete Blood Count)': {
    description: 'A comprehensive blood test that evaluates your overall health by measuring red blood cells, white blood cells, hemoglobin, hematocrit, and platelets. Helps detect infections, anemia, blood disorders, and immune system conditions.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 24,
    category: 'Hematology',
  },
  'Hemoglobin (Hb)': {
    description: 'Measures the protein in red blood cells that carries oxygen throughout your body. Low hemoglobin indicates anemia, while high levels may suggest dehydration or lung conditions. Essential for evaluating oxygen-carrying capacity.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '4 hours',
    parameters: 1,
    category: 'Hematology',
  },
  'ESR (Erythrocyte Sedimentation Rate)': {
    description: 'A non-specific marker of inflammation in the body. Elevated ESR can indicate infections, autoimmune diseases, cancer, or chronic inflammatory conditions. Often used alongside CRP for a comprehensive inflammation assessment.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Hematology',
  },
  'Blood Group & Rh Factor': {
    description: 'Determines your blood type (A, B, AB, or O) and Rh factor (positive or negative). Critical for blood transfusions, pregnancy planning, and organ transplants. A one-time test with lifelong results.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '4 hours',
    parameters: 2,
    category: 'Hematology',
  },
  'Platelet Count': {
    description: 'Measures the number of platelets in your blood that help with clotting. Low counts (thrombocytopenia) increase bleeding risk, while high counts may indicate bone marrow disorders. Important for dengue monitoring.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '4 hours',
    parameters: 1,
    category: 'Hematology',
  },
  'PCV (Packed Cell Volume)': {
    description: 'Also called Hematocrit, this measures the proportion of blood volume occupied by red blood cells. Helps diagnose anemia, polycythemia, and dehydration. An important marker for overall blood health.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '4 hours',
    parameters: 1,
    category: 'Hematology',
  },
  'RBC Count': {
    description: 'Counts the number of red blood cells per microliter of blood. RBCs carry oxygen from lungs to tissues. Abnormal counts can indicate anemia, bone marrow failure, or conditions causing excess red cell production.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '4 hours',
    parameters: 1,
    category: 'Hematology',
  },
  'WBC Count (Total & Differential)': {
    description: 'Measures white blood cells that fight infection. The differential breaks down five WBC types: neutrophils, lymphocytes, monocytes, eosinophils, and basophils. Helps diagnose infections, allergies, and immune disorders.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 6,
    category: 'Hematology',
  },
  'Peripheral Blood Smear': {
    description: 'A microscopic examination of a blood film by a pathologist. Evaluates the shape, size, and appearance of red and white blood cells and platelets. Critical for diagnosing blood cancers, malaria, and unusual cell morphologies.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 1,
    category: 'Hematology',
  },

  // ===== DIABETES & SUGAR =====
  'FBS (Fasting Blood Sugar)': {
    description: 'Measures blood glucose after an overnight fast of 8-12 hours. The gold standard for diabetes screening. Normal is below 100 mg/dL, prediabetes is 100-125 mg/dL, and diabetes is 126 mg/dL or above.',
    sampleType: 'Blood',
    fasting: '8-12 hours fasting required',
    reportTime: '4 hours',
    parameters: 1,
    category: 'Diabetes',
  },
  'PPBS (Post Prandial Blood Sugar)': {
    description: 'Measures blood sugar 2 hours after eating. Shows how well your body processes glucose after meals. Normal is below 140 mg/dL. Essential for managing diabetes alongside FBS.',
    sampleType: 'Blood',
    fasting: 'Test 2 hours after meal',
    reportTime: '4 hours',
    parameters: 1,
    category: 'Diabetes',
  },
  'Random Blood Sugar (RBS)': {
    description: 'A blood glucose test taken at any time of the day regardless of meals. A quick screening tool for diabetes. Values above 200 mg/dL with symptoms strongly suggest diabetes.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '2 hours',
    parameters: 1,
    category: 'Diabetes',
  },
  'HbA1c (Glycated Hemoglobin)': {
    description: 'Reveals your average blood sugar over the past 2-3 months by measuring glucose attached to hemoglobin. The most important test for diabetes management. Target is usually below 7% for diabetics.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 1,
    category: 'Diabetes',
  },
  'GTT (Glucose Tolerance Test)': {
    description: 'A diagnostic test for diabetes and gestational diabetes. Blood sugar is measured fasting and then at intervals after drinking a glucose solution. Shows how efficiently your body handles sugar over time.',
    sampleType: 'Blood',
    fasting: '10-12 hours fasting required',
    reportTime: '24 hours',
    parameters: 3,
    category: 'Diabetes',
  },
  'OGTT - 3 Sample': {
    description: 'Oral Glucose Tolerance Test with three blood samples: fasting, 1-hour, and 2-hour post glucose load. The definitive test for gestational diabetes in pregnancy and for diagnosing impaired glucose tolerance.',
    sampleType: 'Blood',
    fasting: '10-12 hours fasting required',
    reportTime: '24 hours',
    parameters: 3,
    category: 'Diabetes',
  },
  'Fructosamine': {
    description: 'Measures glycated proteins to reflect blood sugar control over the past 2-3 weeks. Useful when HbA1c is unreliable (hemoglobin variants, blood loss). Provides a shorter-term view of glucose control.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Diabetes',
  },
  'Fasting Insulin': {
    description: 'Measures insulin levels after fasting to evaluate insulin resistance and pancreatic function. High fasting insulin with normal glucose suggests early insulin resistance, a precursor to Type 2 diabetes.',
    sampleType: 'Blood',
    fasting: '8-12 hours fasting required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Diabetes',
  },
  'C-Peptide': {
    description: 'Measures a byproduct of insulin production to assess how much insulin your pancreas makes. Differentiates Type 1 from Type 2 diabetes. Also helps evaluate insulinoma and monitor pancreatic function.',
    sampleType: 'Blood',
    fasting: '8 hours fasting preferred',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Diabetes',
  },
  'HOMA-IR': {
    description: 'Homeostatic Model Assessment of Insulin Resistance. Calculated from fasting glucose and insulin levels to quantify insulin resistance. A HOMA-IR above 2.5 suggests significant insulin resistance.',
    sampleType: 'Blood',
    fasting: '8-12 hours fasting required',
    reportTime: '24 hours',
    parameters: 2,
    category: 'Diabetes',
  },
  'Diabetes Basic': {
    description: 'A focused panel for initial diabetes screening including FBS and PPBS. Ideal for routine health checkups and early detection of blood sugar abnormalities. Quick turnaround with essential results.',
    sampleType: 'Blood',
    fasting: '8-10 hours fasting required',
    reportTime: '6 hours',
    parameters: 2,
    category: 'Diabetes',
  },
  'Diabetes Screening': {
    description: 'Comprehensive diabetes panel with FBS, PPBS, and HbA1c. Gives both immediate and long-term glucose picture. Recommended annually for adults over 35 or those with family history of diabetes.',
    sampleType: 'Blood',
    fasting: '8-12 hours fasting required',
    reportTime: '12 hours',
    parameters: 3,
    category: 'Diabetes',
  },
  'Diabetes Advance': {
    description: 'The most comprehensive diabetes evaluation including FBS, PPBS, HbA1c, Fasting Insulin, and C-Peptide. Assesses both sugar levels and insulin production capacity for thorough diabetes management.',
    sampleType: 'Blood',
    fasting: '8-12 hours fasting required',
    reportTime: '24 hours',
    parameters: 5,
    category: 'Diabetes',
  },

  // ===== KIDNEY FUNCTION =====
  'Creatinine': {
    description: 'A key marker of kidney function. Creatinine is a waste product from muscle metabolism filtered by kidneys. Elevated levels suggest impaired kidney function, dehydration, or excessive muscle breakdown.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Kidney',
  },
  'Blood Urea': {
    description: 'Measures urea, a waste product from protein metabolism cleared by kidneys. Elevated levels indicate kidney dysfunction, dehydration, high-protein diet, or gastrointestinal bleeding.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Kidney',
  },
  'BUN (Blood Urea Nitrogen)': {
    description: 'Measures nitrogen in blood from urea breakdown. Together with creatinine, helps evaluate kidney function. The BUN/Creatinine ratio helps differentiate kidney disease from dehydration.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Kidney',
  },
  'Uric Acid': {
    description: 'Measures uric acid levels in blood. High levels cause gout (painful joint inflammation) and increase kidney stone risk. Also elevated in kidney disease, certain cancers, and with some medications.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Kidney',
  },
  'eGFR (Estimated GFR)': {
    description: 'Estimated Glomerular Filtration Rate calculated from creatinine. The single best measure of kidney function. Values below 60 indicate chronic kidney disease. Used to stage kidney disease severity.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Kidney',
  },
  'Electrolytes (Na, K, Cl)': {
    description: 'Measures sodium, potassium, and chloride levels essential for nerve function, muscle contraction, and fluid balance. Imbalances can cause muscle cramps, weakness, irregular heartbeat, and confusion.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 3,
    category: 'Kidney',
  },
  'Serum Electrolytes': {
    description: 'Comprehensive electrolyte panel measuring sodium, potassium, chloride, and bicarbonate. Critical for patients on diuretics, those with heart or kidney disease, and for monitoring IV fluid therapy.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 4,
    category: 'Kidney',
  },
  'RFT (Renal Function Test)': {
    description: 'Complete kidney health panel measuring creatinine, urea, uric acid, electrolytes, and eGFR. Essential for detecting kidney disease, monitoring kidney function, and adjusting medication doses.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 8,
    category: 'Kidney',
  },
  'UPCR': {
    description: 'Urine Protein to Creatinine Ratio from a spot urine sample. Screens for proteinuria without 24-hour urine collection. Important for detecting early kidney damage, especially in diabetics.',
    sampleType: 'Urine',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 2,
    category: 'Kidney',
  },

  // ===== LIVER FUNCTION =====
  'LFT (Liver Function Test)': {
    description: 'Comprehensive liver health panel measuring enzymes (SGPT, SGOT, ALP, GGT), proteins (albumin, globulin), and bilirubin. Detects liver damage, hepatitis, fatty liver, cirrhosis, and drug-induced injury.',
    sampleType: 'Blood',
    fasting: '8-12 hours fasting recommended',
    reportTime: '12 hours',
    parameters: 12,
    category: 'Liver',
  },
  'SGPT (ALT)': {
    description: 'Alanine Aminotransferase, a liver-specific enzyme. Elevated levels are the most sensitive indicator of liver cell damage. Common causes include hepatitis, fatty liver, alcohol use, and medications.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Liver',
  },
  'SGOT (AST)': {
    description: 'Aspartate Aminotransferase found in liver, heart, and muscles. Elevated alongside SGPT suggests liver disease. When SGOT is higher than SGPT, it may indicate alcoholic liver disease or heart damage.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Liver',
  },
  'Alkaline Phosphatase (ALP)': {
    description: 'An enzyme found in liver, bile ducts, and bone. Elevated ALP suggests bile duct obstruction, liver disease, or bone disorders. Important for diagnosing cholestatic liver disease and Pagets disease.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Liver',
  },
  'Bilirubin (Total, Direct, Indirect)': {
    description: 'Measures bilirubin from red blood cell breakdown. Elevated levels cause jaundice (yellowing of skin and eyes). Differentiates between liver disease, bile duct obstruction, and hemolytic conditions.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 3,
    category: 'Liver',
  },
  'Total Protein': {
    description: 'Measures albumin and globulin in blood. Low levels indicate liver disease, kidney disease, or malnutrition. High levels may suggest chronic infection, inflammation, or blood cancers like multiple myeloma.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Liver',
  },
  'Albumin': {
    description: 'The most abundant blood protein, made by the liver. Low albumin indicates liver disease, kidney disease, or malnutrition. Also used to assess nutritional status and disease severity in chronic conditions.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Liver',
  },
  'Globulin': {
    description: 'A group of proteins including immunoglobulins (antibodies). Elevated in chronic infections, autoimmune diseases, and liver cirrhosis. Low levels may indicate immune deficiency or certain blood cancers.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Liver',
  },
  'A/G Ratio': {
    description: 'Albumin to Globulin ratio reflects liver and immune function. A reversed ratio (below 1) suggests liver disease, kidney disease, or chronic infection. Normal ratio is typically 1.2 to 1.6.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Liver',
  },
  'GGT (Gamma GT)': {
    description: 'Gamma-Glutamyl Transferase, elevated in liver and bile duct disease. Particularly sensitive to alcohol use. When elevated with ALP, strongly suggests bile duct problems or alcohol-related liver damage.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Liver',
  },
  'Serum Amylase': {
    description: 'An enzyme produced by the pancreas and salivary glands. Sharply elevated in acute pancreatitis. Also rises in salivary gland diseases, intestinal obstruction, and some medications.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Liver',
  },
  'Lipase': {
    description: 'A pancreatic enzyme more specific than amylase for pancreatitis. Stays elevated longer than amylase, making it more reliable for late diagnosis. The preferred test for suspected pancreatitis.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Liver',
  },
  'LDH': {
    description: 'Lactate Dehydrogenase, an enzyme present in almost all body tissues. Elevated in tissue damage from heart attack, liver disease, blood disorders, or cancer. A non-specific but sensitive damage marker.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Liver',
  },
  'Amylase': {
    description: 'Digestive enzyme primarily from the pancreas. Elevated levels indicate pancreatitis, pancreatic duct obstruction, or salivary gland inflammation. Important for evaluating acute abdominal pain.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Liver',
  },

  // ===== LIPID / CHOLESTEROL =====
  'Lipid Profile': {
    description: 'Complete cholesterol panel measuring Total Cholesterol, LDL, HDL, Triglycerides, VLDL, and ratios. Essential for assessing cardiovascular risk and guiding treatment for heart disease prevention.',
    sampleType: 'Blood',
    fasting: '10-12 hours fasting required',
    reportTime: '12 hours',
    parameters: 8,
    category: 'Cardiology',
  },
  'Total Cholesterol': {
    description: 'Combined measure of all cholesterol types in blood. Desirable level is below 200 mg/dL. Elevated total cholesterol increases risk of heart attack and stroke. A starting point for heart health assessment.',
    sampleType: 'Blood',
    fasting: '10-12 hours fasting required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Cardiology',
  },
  'Triglycerides': {
    description: 'A type of fat in blood that stores unused calories. High triglycerides (above 150 mg/dL) increase heart disease and pancreatitis risk. Strongly affected by diet, alcohol, and obesity.',
    sampleType: 'Blood',
    fasting: '12-14 hours fasting required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Cardiology',
  },
  'HDL Cholesterol': {
    description: 'High-Density Lipoprotein or "good cholesterol" that removes bad cholesterol from arteries. Higher levels (above 60 mg/dL) protect against heart disease. Low HDL is a major cardiovascular risk factor.',
    sampleType: 'Blood',
    fasting: '10-12 hours fasting',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Cardiology',
  },
  'LDL Cholesterol': {
    description: 'Low-Density Lipoprotein or "bad cholesterol" that builds up in artery walls. Optimal is below 100 mg/dL. The primary target for cholesterol-lowering medications to reduce heart disease risk.',
    sampleType: 'Blood',
    fasting: '10-12 hours fasting',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Cardiology',
  },
  'VLDL Cholesterol': {
    description: 'Very Low-Density Lipoprotein carries triglycerides in blood. Elevated VLDL contributes to plaque buildup in arteries. Usually calculated from triglyceride levels as part of a lipid panel.',
    sampleType: 'Blood',
    fasting: '10-12 hours fasting',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Cardiology',
  },
  'Non-HDL Cholesterol': {
    description: 'Total cholesterol minus HDL, capturing all atherogenic (artery-clogging) cholesterol. Some cardiologists consider it a better predictor of heart disease risk than LDL alone.',
    sampleType: 'Blood',
    fasting: '10-12 hours fasting',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Cardiology',
  },
  'TC/HDL Ratio': {
    description: 'Total Cholesterol to HDL ratio, a powerful predictor of heart disease risk. A ratio below 3.5 is ideal. Higher ratios indicate greater cardiovascular risk even when individual numbers look acceptable.',
    sampleType: 'Blood',
    fasting: '10-12 hours fasting',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Cardiology',
  },
  'LDL/HDL Ratio': {
    description: 'Ratio of bad to good cholesterol. Ideally below 2.0. This ratio helps predict heart disease risk more accurately than either value alone. A key metric for cardiovascular health assessment.',
    sampleType: 'Blood',
    fasting: '10-12 hours fasting',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Cardiology',
  },

  // ===== THYROID =====
  'TSH': {
    description: 'Thyroid Stimulating Hormone is the first-line test for thyroid disorders. High TSH suggests hypothyroidism (underactive thyroid), low TSH suggests hyperthyroidism. Affects metabolism, energy, weight, and mood.',
    sampleType: 'Blood',
    fasting: 'Not required, morning preferred',
    reportTime: '12 hours',
    parameters: 1,
    category: 'Thyroid',
  },
  'T3 (Total)': {
    description: 'Triiodothyronine is the active thyroid hormone. Total T3 measures both bound and free forms. Important for diagnosing hyperthyroidism when TSH is low. Affected by pregnancy and medications.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 1,
    category: 'Thyroid',
  },
  'T4 (Total)': {
    description: 'Thyroxine is the main thyroid hormone. Total T4 measures bound and free forms. Elevated in hyperthyroidism, low in hypothyroidism. Best interpreted alongside TSH for accurate thyroid assessment.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 1,
    category: 'Thyroid',
  },
  'Free T3 (FT3)': {
    description: 'Measures unbound, active T3 hormone. More accurate than Total T3 as its unaffected by protein levels. Essential for diagnosing T3 thyrotoxicosis and monitoring thyroid treatment.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 1,
    category: 'Thyroid',
  },
  'Free T4 (FT4)': {
    description: 'Measures unbound, active thyroxine. The most reliable test for thyroid function alongside TSH. Not affected by pregnancy or estrogen-containing medications unlike Total T4.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 1,
    category: 'Thyroid',
  },
  'Thyroid Profile - Free': {
    description: 'Complete thyroid assessment with Free T3, Free T4, and TSH. The most accurate thyroid panel unaffected by protein-binding variations. Recommended for comprehensive thyroid evaluation.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 3,
    category: 'Thyroid',
  },
  'Thyroid Profile - Total': {
    description: 'Thyroid panel with Total T3, Total T4, and TSH. A cost-effective thyroid screening option. Note: Total values can be affected by pregnancy, oral contraceptives, and liver disease.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 3,
    category: 'Thyroid',
  },
  'Thyroid Antibodies (TPO, TG)': {
    description: 'Measures anti-thyroid peroxidase (TPO) and anti-thyroglobulin (TG) antibodies. Elevated in autoimmune thyroid diseases like Hashimotos thyroiditis and Graves disease. Helps identify the cause of thyroid dysfunction.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 2,
    category: 'Thyroid',
  },

  // ===== CARDIAC MARKERS =====
  'Troponin I/T': {
    description: 'The most specific marker for heart muscle damage. Elevated within hours of a heart attack and stays elevated for days. The gold standard for diagnosing myocardial infarction in emergency settings.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '4 hours',
    parameters: 1,
    category: 'Cardiology',
  },
  'CPK-MB': {
    description: 'Creatine Phosphokinase-MB fraction, specific to heart muscle. Rises within 4-6 hours of heart attack and normalizes within 48-72 hours. Used alongside Troponin for cardiac event timing.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Cardiology',
  },
  'CRP (C-Reactive Protein)': {
    description: 'An inflammation marker produced by the liver. Rises rapidly during infections, injuries, and inflammatory conditions. Useful for monitoring disease activity in arthritis, infections, and post-surgical recovery.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Cardiology',
  },
  'hs-CRP': {
    description: 'High-Sensitivity CRP detects low-grade inflammation linked to cardiovascular disease. Values above 3 mg/L indicate high heart disease risk. A powerful predictor of future cardiac events.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 1,
    category: 'Cardiology',
  },
  'Homocysteine': {
    description: 'An amino acid linked to cardiovascular disease when elevated. High homocysteine damages blood vessel walls and promotes blood clots. Often elevated due to B12, B6, or folate deficiency.',
    sampleType: 'Blood',
    fasting: '8-12 hours fasting recommended',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Cardiology',
  },
  'BNP/NT-proBNP': {
    description: 'Brain Natriuretic Peptide released when heart is under stress. The definitive blood test for heart failure diagnosis and monitoring. Higher levels indicate greater heart strain and poorer prognosis.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 1,
    category: 'Cardiology',
  },
  'D-Dimer': {
    description: 'A fibrin degradation product indicating blood clot breakdown. Elevated in deep vein thrombosis (DVT), pulmonary embolism, and DIC. A negative D-Dimer effectively rules out active blood clotting.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Cardiology',
  },

  // ===== VITAMINS & MINERALS =====
  'Iron Studies (Serum Iron, TIBC, Ferritin)': {
    description: 'Complete iron panel measuring Serum Iron, Total Iron Binding Capacity, Transferrin Saturation, and Ferritin (iron stores). Diagnoses iron-deficiency anemia, iron overload, and chronic disease anemia.',
    sampleType: 'Blood',
    fasting: 'Morning sample preferred',
    reportTime: '24 hours',
    parameters: 4,
    category: 'Vitamins',
  },
  'Vitamin B12': {
    description: 'Essential for nerve function, red blood cell production, and DNA synthesis. Deficiency causes fatigue, weakness, numbness, memory problems, and megaloblastic anemia. Common in vegetarians and elderly.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Vitamins',
  },
  'Vitamin D': {
    description: 'Vitamin D (25-hydroxy) is essential for calcium absorption, bone health, and immune function. Deficiency is extremely common in India, causing fatigue, bone pain, weakness, and increased fracture risk.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Vitamins',
  },
  'Vitamin D (25-OH)': {
    description: 'The definitive test for vitamin D status. Levels below 20 ng/mL indicate deficiency, 20-30 is insufficient, above 30 is sufficient. Critical for bone health, immunity, and chronic disease prevention.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Vitamins',
  },
  'Folate (Folic Acid)': {
    description: 'Essential B-vitamin for DNA synthesis and cell division. Deficiency causes megaloblastic anemia and neural tube defects in pregnancy. Critical supplement for women planning pregnancy.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Vitamins',
  },
  'Vitamin B1 (Thiamine)': {
    description: 'Essential for carbohydrate metabolism and nerve function. Deficiency causes beriberi (wet and dry forms) and Wernicke-Korsakoff syndrome. Common in alcoholism and malnutrition.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '48 hours',
    parameters: 1,
    category: 'Vitamins',
  },
  'Vitamin B6': {
    description: 'Important for amino acid metabolism, neurotransmitter synthesis, and immune function. Deficiency causes peripheral neuropathy, dermatitis, and anemia. Often deficient in elderly and alcoholics.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '48 hours',
    parameters: 1,
    category: 'Vitamins',
  },
  'Calcium (Total & Ionized)': {
    description: 'Measures calcium essential for bones, nerves, muscles, and heart. Elevated in hyperparathyroidism and cancer. Low in vitamin D deficiency and kidney disease. Ionized calcium is the active form.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 2,
    category: 'Vitamins',
  },
  'Phosphorus': {
    description: 'Works with calcium for bone health and energy metabolism. Abnormal levels affect bones, kidneys, and parathyroid function. Important to monitor in chronic kidney disease patients.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Vitamins',
  },
  'Magnesium': {
    description: 'Essential mineral for 300+ enzyme reactions, muscle and nerve function, blood sugar control, and blood pressure. Deficiency causes muscle cramps, tremors, abnormal heart rhythms, and fatigue.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Vitamins',
  },
  'Zinc': {
    description: 'Trace mineral vital for immune function, wound healing, taste, smell, and cell division. Deficiency impairs immunity, delays wound healing, and causes hair loss. Common in vegetarians.',
    sampleType: 'Blood',
    fasting: 'Morning fasting sample preferred',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Vitamins',
  },

  // ===== COAGULATION =====
  'Reticulocyte Count': {
    description: 'Measures young red blood cells to assess bone marrow production. High count indicates the marrow is actively making RBCs (response to anemia or bleeding). Low count suggests marrow failure.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 1,
    category: 'Hematology',
  },
  'G6PD': {
    description: 'Tests for Glucose-6-Phosphate Dehydrogenase enzyme deficiency, the most common enzyme deficiency worldwide. Causes hemolytic anemia triggered by certain foods (fava beans), drugs, and infections.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Hematology',
  },
  'PT/INR': {
    description: 'Prothrombin Time and International Normalized Ratio measure blood clotting ability. Essential for monitoring warfarin therapy and diagnosing bleeding disorders. INR target for warfarin is usually 2-3.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 2,
    category: 'Hematology',
  },
  'aPTT': {
    description: 'Activated Partial Thromboplastin Time evaluates the intrinsic clotting pathway. Used to monitor heparin therapy and diagnose bleeding disorders like hemophilia. Prolonged aPTT indicates clotting problems.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Hematology',
  },
  'Bleeding Time (BT)': {
    description: 'Measures how long it takes for a small wound to stop bleeding. Tests platelet function and capillary integrity. Prolonged in platelet disorders, von Willebrand disease, and aspirin use.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '2 hours',
    parameters: 1,
    category: 'Hematology',
  },
  'Clotting Time (CT)': {
    description: 'Measures the time blood takes to clot in a test tube. A basic screening test for clotting disorders. Prolonged in hemophilia, liver disease, and anticoagulant therapy.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '2 hours',
    parameters: 1,
    category: 'Hematology',
  },
  'Fibrinogen': {
    description: 'A clotting factor produced by the liver and also an inflammation marker. Low levels indicate DIC or liver disease. Elevated in inflammation, pregnancy, and heart disease. Critical in bleeding emergencies.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 1,
    category: 'Hematology',
  },

  // ===== HORMONES =====
  'LH (Luteinizing Hormone)': {
    description: 'Regulates reproductive function. In women, LH surge triggers ovulation. In men, it stimulates testosterone production. Abnormal levels indicate PCOS, menopause, pituitary disorders, or infertility.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Hormones',
  },
  'FSH (Follicle Stimulating Hormone)': {
    description: 'Essential for reproductive health. Stimulates egg development in women and sperm production in men. Elevated FSH indicates menopause or ovarian/testicular failure. Low FSH suggests pituitary problems.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Hormones',
  },
  'Prolactin': {
    description: 'Hormone primarily responsible for milk production. Elevated levels (hyperprolactinemia) cause irregular periods, infertility, and breast discharge. May indicate pituitary tumor or medication side effects.',
    sampleType: 'Blood',
    fasting: 'Morning sample preferred',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Hormones',
  },
  'Estradiol (E2)': {
    description: 'The primary female estrogen hormone. Essential for reproductive health, bone density, and cardiovascular protection. Low levels indicate menopause or ovarian insufficiency. Monitored during fertility treatment.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Hormones',
  },
  'Progesterone': {
    description: 'Hormone essential for pregnancy maintenance and menstrual cycle regulation. Measured to confirm ovulation, monitor early pregnancy, and assess luteal phase deficiency. Low levels may cause miscarriage.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Hormones',
  },
  'Testosterone (Total & Free)': {
    description: 'The primary male hormone affecting muscle mass, bone density, libido, and energy. Low testosterone causes fatigue, depression, and sexual dysfunction. Also important in women for PCOS evaluation.',
    sampleType: 'Blood',
    fasting: 'Morning sample required',
    reportTime: '24 hours',
    parameters: 2,
    category: 'Hormones',
  },
  'Serum Testosterone': {
    description: 'Measures total testosterone in blood. Important for evaluating hypogonadism in men and hyperandrogenism in women. Morning levels are most accurate as testosterone follows a daily rhythm.',
    sampleType: 'Blood',
    fasting: 'Morning sample required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Hormones',
  },
  'DHEA-S': {
    description: 'Dehydroepiandrosterone Sulfate, an adrenal androgen. Elevated in PCOS, congenital adrenal hyperplasia, and adrenal tumors. Helps differentiate adrenal from ovarian androgen excess.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Hormones',
  },
  'Cortisol': {
    description: 'The stress hormone produced by adrenal glands. Measured to diagnose Cushings syndrome (excess) and Addisons disease (deficiency). Must be collected at specific times as levels vary throughout the day.',
    sampleType: 'Blood',
    fasting: 'Morning sample (8 AM) required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Hormones',
  },
  'AMH (Anti-Mullerian Hormone)': {
    description: 'The best marker of ovarian reserve and fertility potential. Predicts response to IVF stimulation and time to menopause. Also helps diagnose PCOS (elevated) and premature ovarian failure (low).',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '48 hours',
    parameters: 1,
    category: 'Hormones',
  },
  'Beta-hCG': {
    description: 'Human Chorionic Gonadotropin confirms pregnancy and monitors its progression. Serial measurements track early pregnancy viability. Also used as a tumor marker for certain cancers.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 1,
    category: 'Hormones',
  },
  'Hormonal Basic': {
    description: 'Essential hormone panel including FSH, LH, and Prolactin. A starting point for evaluating menstrual irregularities, infertility, and hormonal imbalances in both men and women.',
    sampleType: 'Blood',
    fasting: 'Morning sample preferred',
    reportTime: '24 hours',
    parameters: 3,
    category: 'Hormones',
  },
  'Hormonal Advance': {
    description: 'Comprehensive hormone evaluation with FSH, LH, Prolactin, Estradiol, Progesterone, and Testosterone. Complete assessment for infertility workup, PCOS, and complex hormonal disorders.',
    sampleType: 'Blood',
    fasting: 'Morning sample preferred',
    reportTime: '24 hours',
    parameters: 6,
    category: 'Hormones',
  },

  // ===== PREGNANCY & PRENATAL =====
  'Dual / Double Marker': {
    description: 'First trimester prenatal screening (11-14 weeks) measuring PAPP-A and free Beta-hCG with NT scan. Screens for Down syndrome (Trisomy 21) and Edwards syndrome (Trisomy 18) risk.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '5-7 days',
    parameters: 2,
    category: 'Pregnancy',
  },
  'Quadruple Marker': {
    description: 'Second trimester screening (15-20 weeks) measuring AFP, hCG, Estriol, and Inhibin-A. Screens for Down syndrome, neural tube defects, and Edwards syndrome. More accurate than double marker for some conditions.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '5-7 days',
    parameters: 4,
    category: 'Pregnancy',
  },
  'ANC (Ante Natal Profile)': {
    description: 'Comprehensive antenatal care panel including CBC, blood group, HIV, HBsAg, VDRL, blood sugar, urine routine, and thyroid. The essential battery of tests for every pregnant woman.',
    sampleType: 'Blood + Urine',
    fasting: 'Fasting preferred',
    reportTime: '24 hours',
    parameters: 15,
    category: 'Pregnancy',
  },

  // ===== TUMOR MARKERS =====
  'PSA (Prostate Specific Antigen)': {
    description: 'The primary screening test for prostate cancer in men. Also elevated in benign prostatic hyperplasia and prostatitis. Regular monitoring recommended for men over 50 or those with family history.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Tumor Markers',
  },
  'Serum PSA': {
    description: 'Measures prostate-specific antigen protein. Values above 4 ng/mL may warrant further investigation. Used for prostate cancer screening, staging, and monitoring treatment response.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Tumor Markers',
  },
  'CA-125': {
    description: 'A tumor marker primarily for ovarian cancer. Also elevated in endometriosis, pelvic inflammatory disease, and pregnancy. Used to monitor ovarian cancer treatment response and recurrence.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Tumor Markers',
  },
  'CA 19-9': {
    description: 'Tumor marker for pancreatic and bile duct cancers. Also elevated in colorectal and gastric cancers. Primarily used for monitoring treatment response rather than screening.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Tumor Markers',
  },
  'CEA': {
    description: 'Carcinoembryonic Antigen, used to monitor colorectal cancer treatment. Also elevated in breast, lung, and pancreatic cancers. Rising CEA after surgery may indicate cancer recurrence.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Tumor Markers',
  },
  'AFP (Alpha-Fetoprotein)': {
    description: 'Tumor marker for liver cancer (hepatocellular carcinoma) and testicular germ cell tumors. Also used in prenatal screening for neural tube defects. Elevated in chronic liver disease.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Tumor Markers',
  },

  // ===== AUTOIMMUNE & ARTHRITIS =====
  'Arthritis Basic Panel': {
    description: 'Initial screening panel for joint inflammation including RA Factor, CRP, ESR, and Uric Acid. Helps differentiate rheumatoid arthritis, gout, and other causes of joint pain.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 4,
    category: 'Autoimmune',
  },
  'RA Factor': {
    description: 'Rheumatoid Factor antibody found in ~80% of rheumatoid arthritis patients. Also positive in Sjogrens syndrome, lupus, and some infections. A negative result does not rule out RA.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 1,
    category: 'Autoimmune',
  },
  'Anti-CCP': {
    description: 'Anti-Cyclic Citrullinated Peptide antibody, highly specific for rheumatoid arthritis. More specific than RA Factor and can be positive years before symptoms appear. Predicts disease severity.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Autoimmune',
  },
  'ANA (Antinuclear Antibody)': {
    description: 'Screens for autoimmune diseases by detecting antibodies against cell nuclei. Positive in lupus (SLE), scleroderma, Sjogrens syndrome, and mixed connective tissue disease. The gateway autoimmune test.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24-48 hours',
    parameters: 1,
    category: 'Autoimmune',
  },

  // ===== INFECTIOUS DISEASES =====
  'HIV - Rapid': {
    description: 'Quick screening test for HIV 1 & 2 antibodies with results in 15-30 minutes. A reactive result needs confirmation with ELISA or Western Blot. Early detection enables timely treatment and prevention.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '1 hour',
    parameters: 1,
    category: 'Infectious',
  },
  'HIV 1 & 2': {
    description: 'Confirmatory test detecting HIV-1 and HIV-2 antibodies and p24 antigen. Fourth-generation tests can detect infection within 2-4 weeks of exposure. Confidential testing with pre and post-test counseling.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Infectious',
  },
  'HBsAg (Hepatitis B)': {
    description: 'Hepatitis B surface antigen, the first marker of active HBV infection. Appears 1-10 weeks after exposure. If positive for more than 6 months, indicates chronic hepatitis B carrier status.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 1,
    category: 'Infectious',
  },
  'HCV - Rapid': {
    description: 'Quick screening for Hepatitis C virus antibodies. HCV is a silent liver disease that can cause cirrhosis and liver cancer if untreated. Modern treatments can cure over 95% of HCV infections.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '1 hour',
    parameters: 1,
    category: 'Infectious',
  },
  'HCV (Hepatitis C)': {
    description: 'Confirmatory test for Hepatitis C virus. Detects HCV antibodies indicating current or past infection. If positive, HCV RNA viral load testing determines active infection requiring treatment.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Infectious',
  },
  'VDRL/RPR (Syphilis)': {
    description: 'Screens for syphilis, a sexually transmitted infection. VDRL is a non-specific test that can be false-positive. Positive results need confirmation with TPHA/FTA-ABS. Essential in pregnancy screening.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 1,
    category: 'Infectious',
  },
  'H3 Viral Marker': {
    description: 'Combined screening for three major viral infections: HIV, Hepatitis B (HBsAg), and Hepatitis C (HCV). A cost-effective pre-surgical and pre-transfusion screening panel.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 3,
    category: 'Infectious',
  },
  'Dengue NS1/IgM/IgG': {
    description: 'Comprehensive dengue panel. NS1 detects early infection (day 1-5), IgM appears day 5-7, IgG indicates past infection or secondary dengue. Essential during monsoon season for fever evaluation.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '4 hours',
    parameters: 3,
    category: 'Infectious',
  },
  'MP Antigen (Malaria)': {
    description: 'Rapid diagnostic test detecting Plasmodium falciparum and vivax malaria antigens. Results in minutes for urgent fever cases. More convenient than microscopic smear for initial screening.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '2 hours',
    parameters: 2,
    category: 'Infectious',
  },
  'Malaria (Antigen & Smear)': {
    description: 'Combined malaria testing with rapid antigen test and peripheral blood smear microscopy. The smear identifies species, quantifies parasites, and detects mixed infections. The gold standard for malaria diagnosis.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 2,
    category: 'Infectious',
  },
  'Typhoid (Widal Test)': {
    description: 'Detects antibodies against Salmonella typhi (typhoid fever). Rising titers in paired samples are more diagnostic than single samples. Culture remains the definitive test for typhoid confirmation.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 4,
    category: 'Infectious',
  },
  'Blood Culture & Sensitivity': {
    description: 'The definitive test for bloodstream infections (sepsis). Identifies the exact bacteria/fungus causing infection and tests which antibiotics will work. Critical for guiding targeted antibiotic therapy.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '48-72 hours',
    parameters: 1,
    category: 'Infectious',
  },

  // ===== URINE TESTS =====
  'Urine Routine & Microscopy': {
    description: 'Complete urine analysis examining color, clarity, pH, protein, glucose, blood, ketones, bilirubin, and microscopic elements (cells, crystals, casts). Screens for UTIs, kidney disease, and diabetes.',
    sampleType: 'Urine (midstream)',
    fasting: 'Not required',
    reportTime: '4 hours',
    parameters: 15,
    category: 'Urine',
  },
  'Urine Culture & Sensitivity': {
    description: 'Identifies the specific bacteria causing urinary tract infection and tests which antibiotics will kill it. Essential for treating recurrent or resistant UTIs. Takes 48-72 hours for complete results.',
    sampleType: 'Urine (midstream clean catch)',
    fasting: 'Not required',
    reportTime: '48-72 hours',
    parameters: 1,
    category: 'Urine',
  },
  'Urine Albumin': {
    description: 'Detects albumin protein in urine, an early sign of kidney damage. Particularly important for diabetics and hypertensives. Microalbuminuria precedes overt kidney disease by years.',
    sampleType: 'Urine',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Urine',
  },
  'Urine Creatinine': {
    description: 'Measures creatinine concentration in urine to assess kidney filtration. Used alongside blood creatinine to calculate creatinine clearance. Also normalizes other urine measurements.',
    sampleType: 'Urine',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 1,
    category: 'Urine',
  },
  'Albumin/Creatinine Ratio (ACR)': {
    description: 'The preferred screening test for early kidney disease in diabetics. A spot urine sample replaces 24-hour collection. ACR above 30 mg/g indicates microalbuminuria and early kidney damage.',
    sampleType: 'Urine (first morning preferred)',
    fasting: 'Not required',
    reportTime: '6 hours',
    parameters: 2,
    category: 'Urine',
  },
  'Urine Pregnancy Test': {
    description: 'Detects human chorionic gonadotropin (hCG) in urine to confirm pregnancy. Most accurate with first morning urine. Can detect pregnancy as early as 1-2 weeks after conception.',
    sampleType: 'Urine (first morning)',
    fasting: 'Not required',
    reportTime: '30 minutes',
    parameters: 1,
    category: 'Urine',
  },

  // ===== SPUTUM TESTS =====
  'Sputum AFB (Acid-Fast Bacilli)': {
    description: 'Microscopic examination for tuberculosis (TB) bacteria in sputum. Three morning samples recommended for best sensitivity. A positive smear indicates active, infectious TB requiring immediate treatment.',
    sampleType: 'Sputum (early morning)',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 1,
    category: 'Sputum',
  },
  'Sputum Culture & Sensitivity': {
    description: 'Grows bacteria from sputum to identify respiratory infections and test antibiotic effectiveness. Essential for pneumonia, bronchitis, and TB. Takes longer but provides definitive pathogen identification.',
    sampleType: 'Sputum',
    fasting: 'Not required',
    reportTime: '48-72 hours',
    parameters: 1,
    category: 'Sputum',
  },
  'GeneXpert MTB/RIF': {
    description: 'Rapid molecular test for tuberculosis that detects TB DNA and rifampicin resistance in 2 hours. Revolutionary for quick TB diagnosis. WHO-recommended as the initial diagnostic test for TB.',
    sampleType: 'Sputum',
    fasting: 'Not required',
    reportTime: '4 hours',
    parameters: 2,
    category: 'Sputum',
  },

  // ===== PACKAGES =====
  'Diabetes Screening Package': {
    description: 'Comprehensive diabetes evaluation with FBS, PPBS, and HbA1c. Covers both immediate blood sugar and long-term glucose control. Recommended annually for adults over 35.',
    sampleType: 'Blood',
    fasting: '8-12 hours fasting required',
    reportTime: '12 hours',
    parameters: 3,
    category: 'Package',
  },
  'Cardiac Risk Profile': {
    description: 'Complete heart health assessment including Lipid Profile, hs-CRP, Homocysteine, and blood sugar. Evaluates all major modifiable risk factors for heart disease. Recommended for adults over 40.',
    sampleType: 'Blood',
    fasting: '10-12 hours fasting required',
    reportTime: '24 hours',
    parameters: 12,
    category: 'Package',
  },
  'Anemia Profile': {
    description: 'Comprehensive anemia workup with CBC, Iron Studies, Vitamin B12, Folate, and Peripheral Smear. Identifies the type and cause of anemia for targeted treatment.',
    sampleType: 'Blood',
    fasting: 'Not required',
    reportTime: '24 hours',
    parameters: 15,
    category: 'Package',
  },
  'Fever Panel': {
    description: 'Targeted tests for common fever causes: CBC, Malaria, Dengue, Typhoid (Widal), Urine Routine, and CRP. Essential workup for prolonged or high-grade fever to identify the infection source.',
    sampleType: 'Blood + Urine',
    fasting: 'Not required',
    reportTime: '12 hours',
    parameters: 10,
    category: 'Package',
  },
  'Master Health Checkup': {
    description: 'The most comprehensive health screening covering CBC, Liver, Kidney, Thyroid, Lipids, Diabetes, Vitamins, Urine, and more. Over 60 parameters for a complete health overview. Annual checkup recommended.',
    sampleType: 'Blood + Urine',
    fasting: '10-12 hours fasting required',
    reportTime: '24-48 hours',
    parameters: 60,
    category: 'Package',
  },
};

export default TEST_DETAILS_MAP;
